---
title: "data manipulation"
output: github_document
---



```{r}
library(tidyverse)
```

## load in the fas litters
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df =  janitor::clean_names(litters_df)
```

## select
choose some columns and not others
```{r}
select(litters_df, group, litter_number)
```

```{r}
select(litters_df, -litter_number)
```

rename columns
```{r}
select(litters_df, GROUP = group, LITTER_NUMBER = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTER_NUMBER = litter_number)
```

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

##fliter

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, gd_of_birth != 20)
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group %in% c("Mod8","Con7"))
```

## mutate

```{r}
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## arrange
```{r}
arrange(litters_df,pups_born_alive)
```

##pipe %>%
```{r}
litter_data_row = read_csv("./data/FAS_litters.csv")
litter_clean_name = janitor::clean_names(litter_data_row)
litter_data_selected = select(litter_clean_name,-pups_survive)
litter_mutated = mutate(litter_data_selected, wt_gain = gd18_weight - gd0_weight)
litter_without_missing = drop_na(litter_mutated, gd0_weight)
litter_without_missing
```

use the pipe instead

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
```







